version: '3'

services:
  app:
    build: ./app
    container_name: 2tier-app
    ports:
      - "80:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
    restart: always

  db:
    build: ./db
    container_name: 2tier-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=nodeapp
      - MYSQL_USER=nodeuser
      - MYSQL_PASSWORD=password123
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: 2tier-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always

volumes:
  mysql-data:
  grafana-data:
